service: training-sls-back
# useDotEnv: true
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: alegra-training

functions:
  hello:
    handler: src/hello.handler
    layers:
      - { Ref: SharedLambdaLayer }
  create-foundation:
    handler: src/create-foundation.handler
    timeout: 15
    layers:
      - { Ref: SharedLambdaLayer }
  authorizer:
    handler: src/authorizer.handler
custom:
  esbuild:
    bundle: true
    minify: true

layers:
  Shared:
    path: dist/layer 
    name: shared-layer
    retain: false
    package:
      patterns:
        - "!./package.json"
        - "!./package-lock.json"

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-latest-layer-version